name: Publish to PyPI

on:
  push:
#    branches:
#      - main
    tags:
      - 'v*'  # Triggers only if you push a tag like v1.0.0

jobs:
  build-and-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set working directory
        run: cd python-simple-email-sender

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: List files in project directory
        run: ls -alh
        working-directory: ./python-simple-email-sender

      - name: Install build dependencies
        run: python -m pip install --upgrade build
        working-directory: ./python-simple-email-sender

      - name: Build the package
        run: python -m build
        working-directory: ./python-simple-email-sender

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
